# Generated by Django 6.0.3 on 2026-06-14 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_bank_statement_alter_client_id_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/id/'),
            preserve_default=False,
        ),
    ]
