# Generated by Django 6.0.3 on 2026-06-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_application_enabled', models.BooleanField(default=True)),
                ('loan_application_message', models.TextField(default='Loan applications are temporarily unavailable. Please try again later.')),
            ],
        ),
    ]
