# Generated by Django 6.0.3 on 2026-06-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemSettings', '0002_alter_systemsetting_loan_application_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='loan_application_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
