# Generated by Django 6.0.3 on 2026-09-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemSettings', '0003_alter_systemsetting_loan_application_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='allow_sending_emails',
            field=models.BooleanField(default=True),
        ),
    ]
