# Generated by Django 6.0.3 on 2026-05-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_pastloansheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
