# Generated by Django 6.0.3 on 2026-06-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_loanpayment_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='defaulting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_payment', 'In Payment Period'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('to_be_reported', 'To Be Reported'), ('reported', 'Reported'), ('paid', 'Paid Off'), ('reloaned', 'Reloaned'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
