# Generated by Django 6.0.3 on 2026-06-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_loan_defaulting_date_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='name_of_paid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
