# Generated by Django 6.0.3 on 2026-06-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingvideo',
            name='category',
            field=models.CharField(choices=[('login', 'Login / Signup'), ('application', 'Loan Application'), ('payment', 'Payment Flow'), ('contract', 'Contract Signing')], default='application', max_length=50),
        ),
    ]
